### ISSUE TITLE
--offset assumes base 16

### ISSUE THREAD

**Issue by alexander-hanel** [OALabs/BlobRunner#10]
blobrunner incorrectly assumes the offset input is in base 16 or hex. For example, the two commands would jump to different offsets, even though they are equivalent. 

```
blobrunner.exe blah.bin --offset 0xC000 
blobrunner.exe blah.bin --offset 3072
```

**Comment by idiom** [comment]
Added check for the offset being prefixed with `0x` and parse as base16.
