### ISSUE TITLE
x64 printf bug

### ISSUE THREAD

**Issue by fnsank** [OALabs/BlobRunner#11]
should be 

#ifdef _WIN64
	printf(" [*] Thread Entry: 0x%016I64x\n", shell_entry);
#else
	printf(" [*] Thread Entry: 0x%08I32x\n", shell_entry);
#endif // _WIN64

**Comment by herrcore** [comment]
loll still open

**Comment by idiom** [comment]
A thread is only created with x64 samples and not x32.
